# This file is a template, and might need editing before it works on your project.
variables:
  DOCKER: "false"
  HELM: "true"

docker-build-master:
  # Official docker image.
  image: docker:latest
  rules:
    - if: '$DOCKER == "true"'
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

docker-build:
  # Official docker image.
  image: docker:latest
  rules:
    - if: '$DOCKER == "true"'
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

helm-publish:
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  rules:
    - if: '$HELM == "true"'
  script:
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm repo add --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD pg253 https://gitlab.com/api/v4/projects/18889048/packages/helm/stable 
    - helm package helm/pg253
    - helm cm-push $(find . -name "pg253-*.tgz" -type f) pg253
