{
 "title": "PG253",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "database", "query": "last_backup" }
  ]
 },
 "panels": [
  {
   "title": "First backup",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "first_backup{database=~\"$database\"} * 1000"
    }
   ]
  },
  {
   "title": "Last backup",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "last_backup{database=~\"$database\"} * 1000"
    }
   ]
  },
  {
   "title": "Backup count",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "count by (database) (backups{database=~\"$database\"})"
    }
   ]
  },
  {
   "title": "Backup list",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "backups{database=~\"$database\"} * 1000"
    }
   ]
  },
  {
   "title": "Backup Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "backup_duration{database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "All backups",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "backups{database=~\"$database\"} * 1000",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s])"
    }
   ]
  },
  {
   "title": "Garbage collector",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(python_gc_collections_total[1m]))",
     "legendFormat": "collections"
    },
    {
     "expr": "sum(rate(python_gc_objects_collected_total[1m]))",
     "legendFormat": "collected per second"
    },
    {
     "expr": "sum(python_gc_objects_uncollectable_total)",
     "legendFormat": "uncollectable"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - process_start_time_seconds"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual" }
   ]
  },
  {
   "title": "Exporter scrape duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  },
  {
   "title": "Open file descriptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_open_fds / process_max_fds",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Current transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "current_bytes_write{database=~\"$database\"}",
     "legendFormat": "Write for '{{database}}'"
    },
    {
     "expr": "current_bytes_read{database=~\"$database\"}",
     "legendFormat": "Read for '{{database}}'"
    }
   ]
  },
  {
   "title": "Current rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(current_bytes_write{database=~\"$database\"}[30s])",
     "legendFormat": "Write for '{{database}}'"
    },
    {
     "expr": "rate(current_bytes_write{database=~\"$database\"}[30s])",
     "legendFormat": "Read for '{{database}}'"
    }
   ]
  },
  {
   "title": "Part uploaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "part_count{database=~\"$database\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "All transfers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "total_bytes_write_total", "legendFormat": "Write" },
    { "expr": "total_bytes_read_total", "legendFormat": "Read" }
   ]
  },
  {
   "title": "All Current rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(total_bytes_write_total[30s])",
     "legendFormat": "Write"
    },
    {
     "expr": "rate(total_bytes_write_total[30s])",
     "legendFormat": "Read"
    }
   ]
  }
 ]
}