apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "pg253.fullname" . }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: Helm
    grafana_dashboard: '1'
  name: grafana-dashboard
data:
  grafana-dashboard.json: |-
  {{- .Files.Get "grafana-dashboard.json" | nindent 4 }}
