apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg253.fullname" . }}
  labels:
    {{- include "pg253.labels" . | nindent 4 }}
data:
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.aws_secret_access_key | b64enc | quote }}
  PGPASSWORD: {{ .Values.pg.password | b64enc | quote }}
